external_components:
  - source:
      type: git
      url: https://github.com/dtill/esphome-components
    components: [systa_reader]
    refresh: 0s

uart:
  id: uart_bus
  tx_pin: GPIO1
  rx_pin: GPIO13
  baud_rate: 9600
  data_bits: 8
  parity: NONE
  stop_bits: 1

systa_reader:
  - id: sysbus_aqua
    uart_id: uart_bus
    log_invalid: true
    systa_device: aqua
  - id: sysbus_modula
    uart_id: uart_bus
    log_invalid: true
    systa_device: modula

sensor:
    # AQUA sensors:
  - platform: systa_reader
    systa_reader_id: sysbus_aqua
    kind: aqua_tsa
    name: "AQUA TSA (Kollektor)"
  - platform: systa_reader
    systa_reader_id: sysbus_aqua
    kind: aqua_tse
    name: "AQUA TSE (Eintritt)"
  - platform: systa_reader
    systa_reader_id: sysbus_aqua
    kind: aqua_twu
    name: "AQUA TWU (unten)"
  - platform: systa_reader
    systa_reader_id: sysbus_aqua
    kind: aqua_tw2
    name: "AQUA TW2 (oben)"
  - platform: systa_reader
    systa_reader_id: sysbus_aqua
    kind: aqua_sol
    name: "AQUA Solare Leistung"
  - platform: systa_reader
    systa_reader_id: sysbus_aqua
    kind: aqua_tag
    name: "AQUA Tagesgewinn"
  - platform: systa_reader
    systa_reader_id: sysbus_aqua
    kind: aqua_gesamt
    name: "AQUA Solargewinn gesamt"
  - platform: systa_reader
    systa_reader_id: sysbus_aqua
    kind: aqua_status_code
    name: "AQUA Status Code"

    # MODULA sensors:
  - platform: systa_reader
    systa_reader_id: sysbus_modula
    kind: modula_two
    name: "MODULA TWO"
  - platform: systa_reader
    systa_reader_id: sysbus_modula
    kind: modula_tbv
    name: "MODULA TBV"
  - platform: systa_reader
    systa_reader_id: sysbus_modula
    kind: modula_tbr
    name: "MODULA TBR"
  - platform: systa_reader
    systa_reader_id: sysbus_modula
    kind: modula_tv
    name: "MODULA TV"
  - platform: systa_reader
    systa_reader_id: sysbus_modula
    kind: modula_tv2
    name: "MODULA TV2"
  - platform: systa_reader
    systa_reader_id: sysbus_modula
    kind: modula_tr
    name: "MODULA TR"
  - platform: systa_reader
    systa_reader_id: sysbus_modula
    kind: modula_tr2
    name: "MODULA TR2"
  - platform: systa_reader
    systa_reader_id: sysbus_modula
    kind: modula_tpo
    name: "MODULA TPO"
  - platform: systa_reader
    systa_reader_id: sysbus_modula
    kind: modula_tpu
    name: "MODULA TPU"
  - platform: systa_reader
    systa_reader_id: sysbus_modula
    kind: modula_tzr
    name: "MODULA TZR"

text_sensor:
  # General BUS Frames in RAW HEX format:
  - platform: systa_reader
    systa_reader_id: sysbus_aqua
    mode: raw
    filter: all
    name: "Systa Raw HEX (ALL)"
  - platform: systa_reader
    systa_reader_id: sysbus_aqua
    mode: raw
    filter: aqua
    name: "Systa Raw HEX (AQUA)"

  # AQUA text sensors:
  - platform: systa_reader
    systa_reader_id: sysbus_aqua
    mode: field
    kind: aqua_status_text
    name: "AQUA Status Text"
  - platform: systa_reader
    systa_reader_id: sysbus_aqua
    mode: field
    kind: aqua_timestamp
    name: "AQUA Zeitstempel"
  - platform: systa_reader
    systa_reader_id: sysbus_aqua
    mode: field
    kind: aqua_display_text
    name: "AQUA Displaytext"

  # MODULA text sensors:
  - platform: systa_reader
    systa_reader_id: sysbus_modula
    mode: field
    kind: modula_timestamp
    name: "MODULA Zeitstempel"