esp32:
  board: esp32dev

external_components:
  - source:
      type: git
      url: https://github.com/dtill/esphome-components
    components: [gdoor]
    refresh: 15m

gdoor:
  id: my_gdoor    # optional set your own id here
  tx_pin: 25      # optional (default 25)
  tx_en_pin: 27   # optional (default 27)
  rx_pin: 22      # optional (default 22)
  rx_sens: 'med'  # optional if rx_pin is 22: 'low', 'med' or 'high' (default 'high')

text_sensor:      # atm returns gdoor formatted string: "action": "BUTTON_RING", "parameters": "0360", "source": "A286FD", "destination": "000000", "type": "OUTDOOR", "busdata": "011011A286FD0360A04A"
  - platform: gdoor
    id: gdoor_bus_message
    name: "GDoor Bus Message"
    gdoor_id: my_gdoor

binary_sensor:
  - platform: gdoor
    id: gdoor_outdoor_button_ring
    name: "GDoor Button Ring"
    gdoor_id: my_gdoor
    busdata: "011011A286FD0360A04A" # example from a BUTTON_RING on OUTDOOR station

binary_sensor:
  - platform: gdoor
    id: gdoor_indoor_button_light
    name: "GDoor Button Light"
    gdoor_id: my_gdoor
    busdata: "011041A286FD0000A18F1E" # example from a BUTTON_LIGHT from INDOOR station